'use client'

import React, { useMemo, useState } from 'react'
import { motion } from 'framer-motion'
import { AlertTriangle, ArrowLeft, Baby, CheckCircle2, ChevronLeft, ChevronRight, FileText, RotateCcw, ShieldAlert, TestTube2 } from 'lucide-react'
import { clsx } from 'clsx'
import type { EmergencyPatient } from '@/types/emergency'
import UniversalCareTransition, { type CareTransitionData } from './UniversalCareTransition'
import UniversalLabNotebook, { UNIVERSAL_LAB_RESULTS_KEY } from './UniversalLabNotebook'
import { UNIVERSAL_ASSESSMENT_ANSWER_KEY } from './UniversalClinicalAssessment'

export const HELLP_CASE_KEY = 'hellp_caso_estruturado'
const stages = ['hellp_contexto', 'hellp_sinais_gravidade', 'hellp_laboratorio', 'hellp_interpretacao', 'hellp_estabilizacao', 'hellp_plano_obstetrico', 'hellp_aguarda_cuidado_critico'] as const
type Stage = typeof stages[number]
type HellpData = {
  gestationalAge?: string; postpartum?: boolean; postpartumHours?: string; systolic?: number; diastolic?: number
  obstetricPressureConfirmed?: boolean; gestationalBand?: 'gte34' | '24to34' | 'lt24'
  symptoms?: string[]; danger?: string[]; platelets?: string; ast?: string; alt?: string; ldh?: string; bilirubin?: string; creatinine?: string
  smear?: string; proteinuria?: string; interpretation?: 'compatible' | 'partial' | 'unlikely'; stabilization?: string[]; obstetricPlan?: string[]
  fetalAssessment?: string[]; deliveryIndications?: string[]
  completedAt?: string
}

const parse = (raw?: string): HellpData => { try { return raw ? JSON.parse(raw) : {} } catch { return {} } }
const toggle = (list: string[] = [], value: string) => list.includes(value) ? list.filter(item => item !== value) : [...list, value]
const symptoms = [['epigastric', 'Dor epigástrica ou no quadrante superior direito'], ['nausea', 'Náuseas ou vômitos após a metade da gestação'], ['headache', 'Cefaleia persistente ou sintomas visuais'], ['dyspnea', 'Dispneia, ortopneia ou dor torácica'], ['edema', 'Edema súbito ou ganho ponderal recente'], ['bleeding', 'Sangramento, hematúria, petéquias ou equimoses'], ['malaise', 'Mal-estar intenso ou sintomas inespecíficos']] as const
const dangers = [['eclampsia', 'Convulsão ou rebaixamento do nível de consciência'], ['severe_bp', 'PA ≥160/110 mmHg persistente ou emergência hipertensiva'], ['pulmonary', 'Edema pulmonar ou hipoxemia'], ['shock', 'Choque, sangramento importante ou suspeita de CIVD'], ['liver', 'Dor hepática intensa, defesa ou suspeita de hematoma/ruptura'], ['renal', 'Oligúria importante ou disfunção renal progressiva'], ['fetal', 'Comprometimento fetal agudo']] as const
const stabilization = [['obstetric', 'Acionar obstetrícia, anestesia, neonatologia e unidade crítica'], ['monitor', 'Monitorização contínua, dois acessos e balanço/diurese horária'], ['magnesium', 'Sulfato de magnésio: ataque 4 g EV em 5–15 min, seguido de 1 g/h conforme protocolo'], ['toxicity', 'Monitorar respiração, reflexos e diurese; se toxicidade, gluconato de cálcio 10%, 10 mL EV lentamente'], ['bp', 'PA grave persistente por cerca de 15 min: tratar prontamente e titular para 140–150/90–100 mmHg'], ['blood', 'Tipagem, prova de compatibilidade e planejamento de hemocomponentes'], ['fluids', 'Fluidos com cautela; evitar expansão indiscriminada e vigiar edema pulmonar'], ['fetal', 'Avaliar vitalidade fetal sem atrasar estabilização materna']] as const
const obstetric = [['delivery', 'Planejar resolução da gestação após estabilização materna'], ['route', 'Definir via de parto por indicação obstétrica, condições maternas/fetais e colo'], ['steroid', 'Se prematuridade e tempo clínico permitirem, avaliar corticoide antenatal para maturação fetal'], ['serial', 'Repetir hemograma, plaquetas, função hepática/renal e coagulação em 6–12 h ou antes se piora'], ['differential', 'Revisar diagnósticos diferenciais e complicações hepáticas/hematológicas'], ['postpartum', 'Manter vigilância no puerpério; alterações podem piorar nas primeiras horas após o parto']] as const
const fetalAssessment = [['ctg','Cardiotocografia quando aplicável'],['ultrasound','Ultrassonografia obstétrica'],['doppler','Doppler fetal/placentário conforme indicação clínica']] as const
const deliveryIndications = [['eclampsia','Eclâmpsia ou deterioração neurológica'],['hellp','HELLP completa ou em progressão'],['pulmonary','Edema pulmonar'],['abruption','Suspeita de descolamento prematuro de placenta'],['fetal','Comprometimento fetal'],['refractory_bp','Hipertensão grave refratária'],['renal','Disfunção renal progressiva'],['dic','CIVD, sangramento ou deterioração hepática']] as const

const Option = ({ selected, label, danger, onClick }: { selected: boolean; label: string; danger?: boolean; onClick: () => void }) => <button type="button" aria-pressed={selected} onClick={onClick} className={clsx('flex items-start gap-3 rounded-2xl border p-4 text-left font-bold transition-all', selected ? danger ? 'border-red-500 bg-red-50 ring-2 ring-red-100' : 'border-violet-600 bg-violet-50 ring-2 ring-violet-100' : 'border-slate-200 bg-white hover:border-violet-300')}><span className={clsx('mt-0.5 flex h-6 w-6 shrink-0 items-center justify-center rounded-full border', selected ? danger ? 'border-red-600 bg-red-600 text-white' : 'border-violet-700 bg-violet-700 text-white' : 'border-slate-300 text-transparent')}><CheckCircle2 className="h-4 w-4" /></span><span className="text-slate-950">{label}</span></button>

interface Props { patient: EmergencyPatient; initialStep: string; initialHistory: string[]; initialAnswers: Record<string, string>; onUpdate: (patientId: string, currentStep: string, history: string[], answers: Record<string, string>, progress: number, riskGroup?: string) => void; onComplete: () => void; onBack?: () => void; onOpenReport?: () => void }

const HELLPFlowchartInteractive: React.FC<Props> = ({ patient, initialStep, initialHistory, initialAnswers, onUpdate, onComplete, onBack, onOpenReport }) => {
  const first = stages.includes(initialStep as Stage) ? initialStep as Stage : 'hellp_contexto'
  const [stage, setStage] = useState<Stage>(first)
  const [history, setHistory] = useState(initialHistory.filter(item => stages.includes(item as Stage)))
  const [answers, setAnswers] = useState(initialAnswers)
  const [data, setData] = useState<HellpData>(() => parse(initialAnswers[HELLP_CASE_KEY]))
  const [notice, setNotice] = useState('')
  const [done, setDone] = useState(Boolean(parse(initialAnswers[HELLP_CASE_KEY]).completedAt))
  const transitionKey = '__care_transition_hellp'
  const transition = useMemo<CareTransitionData | null>(() => { try { return answers[transitionKey] ? JSON.parse(answers[transitionKey]) : null } catch { return null } }, [answers])
  const progress = done ? 100 : Math.round(((stages.indexOf(stage) + 1) / stages.length) * 100)
  const update = (patch: Partial<HellpData>) => setData(previous => ({ ...previous, ...patch }))
  const persist = (next: Stage, patch: Partial<HellpData> = {}) => { const nextData = { ...data, ...patch }; const nextHistory = [...history, stage]; const nextAnswers = { ...answers, [HELLP_CASE_KEY]: JSON.stringify(nextData) }; setData(nextData); setHistory(nextHistory); setStage(next); setAnswers(nextAnswers); setNotice(''); onUpdate(patient.id, next, nextHistory, nextAnswers, Math.round(((stages.indexOf(next) + 1) / stages.length) * 100), 'Síndrome HELLP / emergência obstétrica'); window.scrollTo({ top: 0, behavior: 'smooth' }) }
  const saveLabs = (serialized: string) => { const next = { ...answers, [UNIVERSAL_LAB_RESULTS_KEY]: serialized, [HELLP_CASE_KEY]: JSON.stringify(data) }; setAnswers(next); onUpdate(patient.id, stage, history, next, progress, 'Síndrome HELLP / emergência obstétrica') }
  const saveTransition = (value: CareTransitionData) => { const next = { ...answers, [transitionKey]: JSON.stringify(value), [HELLP_CASE_KEY]: JSON.stringify(data) }; setAnswers(next); onUpdate(patient.id, stage, history, next, progress, 'Síndrome HELLP / emergência obstétrica') }
  const finish = (value: CareTransitionData) => { const nextData = { ...data, completedAt: new Date().toISOString() }; const next = { ...answers, [transitionKey]: JSON.stringify(value), [HELLP_CASE_KEY]: JSON.stringify(nextData) }; setData(nextData); setAnswers(next); setDone(true); onUpdate(patient.id, stage, [...history, stage], next, 100, 'Síndrome HELLP / emergência obstétrica'); window.scrollTo({ top: 0, behavior: 'smooth' }) }
  const back = () => { if (done) { setDone(false); return } if (!history.length) { onBack?.(); return } const previous = history[history.length - 1] as Stage; const nextHistory = history.slice(0, -1); setHistory(nextHistory); setStage(previous); onUpdate(patient.id, previous, nextHistory, answers, Math.max(8, progress - 14), patient.emergencyState.riskGroup) }
  const restart = () => { const kept: Record<string, string> = {}; if (answers[UNIVERSAL_ASSESSMENT_ANSWER_KEY]) kept[UNIVERSAL_ASSESSMENT_ANSWER_KEY] = answers[UNIVERSAL_ASSESSMENT_ANSWER_KEY]; setStage('hellp_contexto'); setHistory([]); setAnswers(kept); setData({}); setDone(false); onUpdate(patient.id, 'hellp_contexto', [], kept, 8, 'Emergência obstétrica') }
  const titles: Record<Stage, [string, string]> = { hellp_contexto: ['Contexto obstétrico', 'Reconheça gestação ou puerpério e registre a pressão sem excluir HELLP por PA normal.'], hellp_sinais_gravidade: ['Sintomas e ameaças imediatas', 'Identifique deterioração materna ou fetal antes da confirmação laboratorial.'], hellp_laboratorio: ['Investigação laboratorial dirigida', 'Registre hemólise, enzimas hepáticas, plaquetas, rim e coagulação.'], hellp_interpretacao: ['Compatibilidade com síndrome HELLP', 'Integre clínica, tendência e laboratório; formas incompletas também podem deteriorar.'], hellp_estabilizacao: ['Estabilização materna simultânea', 'Trate convulsão/hipertensão grave e organize cuidado crítico sem esperar todos os resultados.'], hellp_plano_obstetrico: ['Plano obstétrico definitivo', 'A resolução é planejada após estabilização, com via definida pelo cenário obstétrico.'], hellp_aguarda_cuidado_critico: ['Transição para cuidado obstétrico crítico', 'O atendimento permanece ativo até a passagem formal do caso.'] }
  const [title, subtitle] = titles[stage]

  return <div className="min-h-screen bg-gradient-to-b from-slate-50 via-white to-violet-50/50 pb-12">
    <nav className="sticky top-0 z-50 border-b border-slate-200 bg-white/90 backdrop-blur-xl"><div className="mx-auto flex max-w-7xl items-center justify-between gap-3 px-4 py-4"><div><p className="font-black text-slate-950">{patient.name}</p><p className="text-xs font-semibold text-slate-500">Emergência obstétrica · {progress}%</p></div><div className="flex flex-wrap gap-2"><button type="button" onClick={onComplete} className="rounded-xl border border-slate-300 px-3 py-2 text-sm font-bold"><ChevronLeft className="mr-1 inline h-4 w-4" />Dashboard</button><button type="button" onClick={back} className="rounded-xl border border-amber-300 bg-amber-50 px-3 py-2 text-sm font-bold text-amber-950"><ArrowLeft className="mr-1 inline h-4 w-4" />Voltar</button><button type="button" onClick={restart} className="rounded-xl border border-violet-300 bg-violet-50 px-3 py-2 text-sm font-bold text-violet-950"><RotateCcw className="mr-1 inline h-4 w-4" />Reiniciar</button></div></div></nav>
    <header className="relative overflow-hidden bg-gradient-to-r from-violet-900 via-fuchsia-800 to-rose-700 px-5 py-7 text-white shadow-xl"><div className="mx-auto flex max-w-6xl items-center gap-4"><span className="rounded-2xl bg-white/15 p-3"><Baby className="h-8 w-8" /></span><div className="flex-1"><p className="text-xs font-black uppercase tracking-[0.2em] text-white/70">Protocolo interativo · Síndrome HELLP</p><h1 className="mt-1 text-2xl font-black sm:text-3xl">{title}</h1><p className="mt-1 text-sm text-white/85">{subtitle}</p></div></div><div className="absolute bottom-0 left-0 h-1.5 bg-white/35" style={{ width: `${progress}%` }} /></header>
    <main className="mx-auto mt-7 max-w-6xl px-4 sm:px-6">
      {done ? <motion.div initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} className="space-y-6"><section className="rounded-3xl bg-gradient-to-br from-emerald-600 to-teal-700 p-7 text-white shadow-xl"><CheckCircle2 className="h-12 w-12" /><h2 className="mt-4 text-3xl font-black">Plano HELLP registrado</h2><p className="mt-2 max-w-3xl text-emerald-50">Avaliação materna e fetal, exames, estabilização, plano obstétrico e passagem ao cuidado crítico foram preservados no atendimento.</p></section><div className="grid gap-3 sm:grid-cols-2">{onOpenReport && <button type="button" onClick={onOpenReport} className="rounded-xl border border-violet-300 bg-white px-5 py-4 font-extrabold text-violet-900"><FileText className="mr-2 inline h-5 w-5" />Abrir relatório</button>}<button type="button" onClick={onComplete} className="rounded-xl bg-violet-800 px-5 py-4 font-extrabold text-white">Concluir e ir ao dashboard</button></div></motion.div> : <motion.section key={stage} initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} className="space-y-6 rounded-3xl border border-slate-200 bg-white p-5 shadow-xl sm:p-7">
        {stage === 'hellp_contexto' && <><div className="rounded-2xl border border-amber-300 bg-amber-50 p-4 text-amber-950"><AlertTriangle className="mr-2 inline h-5 w-5" /><strong>Não descarte HELLP por PA pouco elevada ou proteinúria ausente.</strong> O quadro pode aparecer antes ou depois do parto e exige integração clínica/laboratorial.</div><div className="grid gap-4 sm:grid-cols-2"><label className="rounded-2xl border border-slate-200 bg-slate-50 p-4 font-bold">Idade gestacional<input value={data.gestationalAge || ''} onChange={event => update({ gestationalAge: event.target.value })} placeholder="Ex.: 32 semanas e 4 dias" className="mt-2 w-full rounded-xl border border-slate-300 bg-white px-4 py-3" /></label><Option selected={Boolean(data.postpartum)} label="Paciente no puerpério" onClick={() => update({ postpartum: !data.postpartum })} /></div>{data.postpartum && <label className="block rounded-2xl border border-slate-200 p-4 font-bold">Tempo desde o parto<input value={data.postpartumHours || ''} onChange={event => update({ postpartumHours: event.target.value })} placeholder="Ex.: 18 horas" className="mt-2 w-full rounded-xl border border-slate-300 px-4 py-3" /></label>}<div className="grid gap-4 sm:grid-cols-2"><label className="font-bold">PAS<input type="number" value={data.systolic ?? ''} onChange={event => update({ systolic: event.target.value ? Number(event.target.value) : undefined, obstetricPressureConfirmed: false })} className="mt-2 w-full rounded-xl border border-slate-300 px-4 py-3" /></label><label className="font-bold">PAD<input type="number" value={data.diastolic ?? ''} onChange={event => update({ diastolic: event.target.value ? Number(event.target.value) : undefined, obstetricPressureConfirmed: false })} className="mt-2 w-full rounded-xl border border-slate-300 px-4 py-3" /></label></div>{((data.systolic||0)>=160||(data.diastolic||0)>=110)&&<Option selected={Boolean(data.obstetricPressureConfirmed)} label="Hipertensão grave confirmada como persistente por aproximadamente 15 minutos" danger onClick={()=>update({obstetricPressureConfirmed:!data.obstetricPressureConfirmed})}/>}<button type="button" disabled={(!data.gestationalAge && !data.postpartum)||(((data.systolic||0)>=160||(data.diastolic||0)>=110)&&!data.obstetricPressureConfirmed)} onClick={() => persist('hellp_sinais_gravidade')} className="w-full rounded-xl bg-violet-800 px-5 py-4 font-extrabold text-white disabled:bg-slate-300">Avaliar sintomas e gravidade <ChevronRight className="inline h-5 w-5" /></button></>}
        {stage === 'hellp_sinais_gravidade' && <><div><h2 className="mb-3 font-black">Apresentação clínica</h2><div className="grid gap-3 md:grid-cols-2">{symptoms.map(([id, label]) => <Option key={id} selected={(data.symptoms || []).includes(id)} label={label} onClick={() => update({ symptoms: toggle(data.symptoms, id) })} />)}</div></div><div><h2 className="mb-3 font-black text-red-800">Ameaças imediatas</h2><div className="grid gap-3 md:grid-cols-2">{dangers.map(([id, label]) => <Option key={id} selected={(data.danger || []).includes(id)} label={label} danger onClick={() => update({ danger: toggle(data.danger, id) })} />)}</div></div><button type="button" onClick={() => persist((data.danger || []).length ? 'hellp_estabilizacao' : 'hellp_laboratorio')} className="w-full rounded-xl bg-violet-800 px-5 py-4 font-extrabold text-white">{(data.danger || []).length ? 'Iniciar estabilização sem aguardar exames' : 'Prosseguir para exames'} <ChevronRight className="inline h-5 w-5" /></button></>}
        {stage === 'hellp_laboratorio' && <><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{([['platelets','Plaquetas','/mm³'],['ast','TGO/AST','U/L'],['alt','TGP/ALT','U/L'],['ldh','LDH','U/L'],['bilirubin','Bilirrubina total','mg/dL'],['creatinine','Creatinina','mg/dL']] as const).map(([key,label,unit]) => <label key={key} className="rounded-xl border border-slate-200 bg-slate-50 p-3 text-sm font-bold">{label}<div className="mt-2 flex"><input value={data[key] || ''} onChange={event => update({ [key]: event.target.value })} className="min-w-0 flex-1 rounded-l-lg border border-slate-300 px-3 py-2" /><span className="rounded-r-lg border border-l-0 border-slate-300 bg-white px-2 py-2 text-xs text-slate-500">{unit}</span></div></label>)}</div><div className="grid gap-3 sm:grid-cols-2"><label className="font-bold">Esfregaço/hemólise<input value={data.smear || ''} onChange={event => update({ smear: event.target.value })} placeholder="Esquizócitos, haptoglobina, reticulócitos..." className="mt-2 w-full rounded-xl border border-slate-300 px-4 py-3" /></label><label className="font-bold">Proteinúria e urina<input value={data.proteinuria || ''} onChange={event => update({ proteinuria: event.target.value })} placeholder="Relação proteína/creatinina, EAS..." className="mt-2 w-full rounded-xl border border-slate-300 px-4 py-3" /></label></div><UniversalLabNotebook value={answers[UNIVERSAL_LAB_RESULTS_KEY]} onChange={saveLabs} defaultOpen suggestedTests={['Hemograma/plaquetas','LDH','Bilirrubinas','TGO/AST','TGP/ALT','Creatinina','TAP/TTPa','Fibrinogênio','Proteinúria']} /><button type="button" onClick={() => persist('hellp_interpretacao')} className="w-full rounded-xl bg-violet-800 px-5 py-4 font-extrabold text-white">Interpretar conjunto clínico e laboratorial</button></>}
        {stage === 'hellp_interpretacao' && <><div className="rounded-2xl border border-violet-200 bg-violet-50 p-5 text-violet-950"><TestTube2 className="mr-2 inline h-5 w-5" /><strong>Apoio laboratorial clássico:</strong> hemólise (esfregaço alterado, bilirrubina &gt;1,2 mg/dL ou LDH &gt;600 U/L), transaminases elevadas e plaquetopenia. Tendência de piora e formas incompletas exigem vigilância.</div><div className="grid gap-3">{([['compatible','Conjunto compatível com HELLP'],['partial','HELLP parcial ou suspeita em evolução'],['unlikely','Critérios atuais não sustentam HELLP; manter diferencial e reavaliação']] as const).map(([id,label]) => <Option key={id} selected={data.interpretation === id} label={label} danger={id !== 'unlikely'} onClick={() => update({ interpretation: id })} />)}</div><button type="button" disabled={!data.interpretation} onClick={() => data.interpretation === 'unlikely' ? persist('hellp_plano_obstetrico') : persist('hellp_estabilizacao')} className="w-full rounded-xl bg-violet-800 px-5 py-4 font-extrabold text-white disabled:bg-slate-300">Registrar interpretação e continuar</button></>}
        {stage === 'hellp_estabilizacao' && <><div className="rounded-2xl border border-red-300 bg-red-50 p-5 text-red-950"><ShieldAlert className="mr-2 inline h-5 w-5" /><strong>Trabalho simultâneo:</strong> estabilização, prevenção de eclâmpsia, controle pressórico, avaliação fetal e preparo obstétrico avançam em paralelo.</div><div className="grid gap-3 md:grid-cols-2">{stabilization.map(([id,label]) => <Option key={id} selected={(data.stabilization || []).includes(id)} label={label} danger={['magnesium','bp'].includes(id)} onClick={() => update({ stabilization: toggle(data.stabilization, id) })} />)}</div><button type="button" disabled={(data.stabilization || []).length < 5} onClick={() => persist('hellp_plano_obstetrico')} className="w-full rounded-xl bg-red-700 px-5 py-4 font-extrabold text-white disabled:bg-slate-300">Avançar para plano obstétrico</button></>}
        {stage === 'hellp_plano_obstetrico' && <><h2 className="font-black">Faixa gestacional</h2><div className="grid gap-3 md:grid-cols-3">{([['gte34','34 semanas ou mais'],['24to34','24 a 33 semanas e 6 dias'],['lt24','Abaixo de 24 semanas']] as const).map(([id,label])=><Option key={id} selected={data.gestationalBand===id} label={label} onClick={()=>update({gestationalBand:id})}/>)}</div><h2 className="font-black">Avaliação fetal registrada</h2><div className="grid gap-3 md:grid-cols-3">{fetalAssessment.map(([id,label])=><Option key={id} selected={(data.fetalAssessment||[]).includes(id)} label={label} onClick={()=>update({fetalAssessment:toggle(data.fetalAssessment,id)})}/>)}</div><h2 className="font-black">Indicações de resolução sem postergação</h2><div className="grid gap-3 md:grid-cols-2">{deliveryIndications.map(([id,label])=><Option key={id} selected={(data.deliveryIndications||[]).includes(id)} label={label} danger onClick={()=>update({deliveryIndications:toggle(data.deliveryIndications,id)})}/>)}</div><div className="grid gap-3 md:grid-cols-2">{obstetric.map(([id,label]) => <Option key={id} selected={(data.obstetricPlan || []).includes(id)} label={label} onClick={() => update({ obstetricPlan: toggle(data.obstetricPlan, id) })} />)}</div><div className="rounded-2xl border border-amber-300 bg-amber-50 p-4 text-sm text-amber-950"><strong>Segurança:</strong> não usar IECA, BRA, alisquireno ou nifedipino de ação imediata. Evitar nitroprussiato salvo exceção extrema e especializada, queda pressórica abrupta e extremos de volume. Corticoide antenatal é para maturação fetal, não para “tratar HELLP”.</div><button type="button" disabled={!data.gestationalBand||(data.fetalAssessment||[]).length<1||(data.obstetricPlan || []).length < 3} onClick={() => persist('hellp_aguarda_cuidado_critico')} className="w-full rounded-xl bg-violet-800 px-5 py-4 font-extrabold text-white disabled:bg-slate-300">Solicitar cuidado obstétrico crítico</button></>}
        {stage === 'hellp_aguarda_cuidado_critico' && <UniversalCareTransition destination="icu" context="hellp pré-eclâmpsia grave obstétrica" value={transition} onChange={saveTransition} onConfirmed={finish} />}
        {notice && <p className="rounded-xl border border-amber-300 bg-amber-50 p-3 text-amber-950">{notice}</p>}
        <button type="button" onClick={back} className="inline-flex items-center gap-2 rounded-xl border border-slate-300 px-4 py-3 font-bold"><ArrowLeft className="h-4 w-4" />Voltar</button>
      </motion.section>}
    </main>
  </div>
}

export default HELLPFlowchartInteractive
