'use client'

import React, { useState } from 'react'
import { AlertTriangle, ArrowLeft, Brain, CheckCircle2, ChevronLeft, FileText, RotateCcw } from 'lucide-react'
import { clsx } from 'clsx'
import type { EmergencyPatient } from '@/types/emergency'
import UniversalCareTransition, { type CareTransitionData } from './UniversalCareTransition'
import UniversalLabNotebook, { UNIVERSAL_LAB_RESULTS_KEY } from './UniversalLabNotebook'
import { UNIVERSAL_ASSESSMENT_ANSWER_KEY } from './UniversalClinicalAssessment'

export const HSA_CASE_ANSWER_KEY = 'hsa_caso_estruturado'
const stages = ['hsa_reconhecimento', 'hsa_imagem', 'hsa_estabilizacao', 'hsa_tratamento_aneurisma', 'hsa_destino'] as const
type Stage = typeof stages[number]
type HsaData = {
  findings?: string[]
  initialMeasures?: string[]
  ctResult?: 'confirmed' | 'negative_high_suspicion' | 'alternative'
  vascularImaging?: string
  additionalInvestigation?: string
  currentPressure?: string
  pressureTarget?: string
  pressureAgent?: string
  stabilization?: string[]
  aneurysmPlan?: string
  definitiveTiming?: boolean
  surveillance?: string[]
  disposition?: string
  completedAt?: string
}

const parse = (raw?: string): HsaData => { try { return raw ? JSON.parse(raw) as HsaData : {} } catch { return {} } }
const toggle = (list: string[] = [], value: string) => list.includes(value) ? list.filter(item => item !== value) : [...list, value]
const recognition = [['thunderclap','Cefaleia súbita e máxima em segundos ou minutos'],['meningism','Rigidez de nuca ou fotofobia'],['vomiting','Náuseas ou vômitos intensos'],['consciousness','Síncope ou alteração do nível de consciência'],['seizure','Convulsão'],['deficit','Déficit neurológico focal']] as const
const initialMeasures = [['abcde','ABCDE, glicemia e exame neurológico seriado'],['monitor','Monitorização cardíaca, oximetria e pressão seriada'],['access','Acessos venosos e coletas sem atrasar imagem'],['oxygen','Oxigênio somente diante de hipoxemia'],['analgesia','Analgesia e controle de náusea sem mascarar deterioração'],['specialist','Neurocirurgia/neurointervenção e regulação acionadas precocemente']] as const
const stabilization = [['nimodipine','Nimodipino enteral precoce conforme protocolo, com ajuste se hipotensão'],['euvolemia','Manter euvolemia; não realizar hipervolemia profilática'],['glucose_temp','Evitar febre e extremos glicêmicos'],['antithrombotic','Revisar e reverter anticoagulação quando indicada'],['seizure','Tratar convulsão; profilaxia apenas em situações selecionadas'],['neuro','Exame neurológico e pupilas reavaliados em série']] as const
const surveillance = [['rebleeding','Ressangramento e deterioração neurológica'],['hydrocephalus','Hidrocefalia aguda e necessidade de derivação'],['dci','Isquemia cerebral tardia/vasoespasmo'],['sodium','Sódio, balanço hídrico e função renal'],['seizure','Convulsões e alteração de consciência'],['cardiopulmonary','Complicações cardiopulmonares e perfusão']] as const

function Choice({ selected, title, description, danger, disabled, onClick }: { selected:boolean; title:string; description?:string; danger?:boolean; disabled?:boolean; onClick:()=>void }) {
  return <button type="button" disabled={disabled} aria-pressed={selected} onClick={onClick} className={clsx('rounded-2xl border p-4 text-left transition', disabled && 'cursor-not-allowed opacity-45', selected ? danger ? 'border-red-500 bg-red-50 ring-2 ring-red-100' : 'border-violet-700 bg-violet-50 ring-2 ring-violet-100' : 'border-slate-200 bg-white hover:border-violet-300')}><span className="flex gap-3"><span className={clsx('mt-0.5 flex h-6 w-6 shrink-0 items-center justify-center rounded-full border', selected ? 'border-violet-700 bg-violet-700 text-white' : 'border-slate-300 text-transparent')}><CheckCircle2 className="h-4 w-4" /></span><span><strong className="block text-slate-950">{title}</strong>{description && <span className="mt-1 block text-sm leading-relaxed text-slate-600">{description}</span>}</span></span></button>
}

interface Props { patient: EmergencyPatient; initialStep:string; initialHistory:string[]; initialAnswers:Record<string,string>; onUpdate:(patientId:string,currentStep:string,history:string[],answers:Record<string,string>,progress:number,riskGroup?:string)=>void; onComplete:()=>void; onBack?:()=>void; onOpenReport?:()=>void }

export default function SubarachnoidHemorrhageFlowchartInteractive({ patient, initialStep, initialHistory, initialAnswers, onUpdate, onComplete, onBack, onOpenReport }: Props) {
  const initial = stages.includes(initialStep as Stage) ? initialStep as Stage : 'hsa_reconhecimento'
  const [stage,setStage] = useState<Stage>(initial)
  const [history,setHistory] = useState(initialHistory.filter(item => stages.includes(item as Stage)))
  const [answers,setAnswers] = useState(initialAnswers)
  const [data,setData] = useState<HsaData>(()=>parse(initialAnswers[HSA_CASE_ANSWER_KEY]))
  const [done,setDone] = useState(Boolean(parse(initialAnswers[HSA_CASE_ANSWER_KEY]).completedAt))
  const [transition,setTransition] = useState<CareTransitionData|null>(()=>{try{return initialAnswers.__care_transition_hsa_destino?JSON.parse(initialAnswers.__care_transition_hsa_destino):null}catch{return null}})
  const progress = done ? 100 : Math.round(((stages.indexOf(stage)+1)/stages.length)*100)
  const update = (patch:Partial<HsaData>) => setData(previous=>({...previous,...patch}))
  const persist = (next:Stage, patch:Partial<HsaData>={}) => { const nextData={...data,...patch}; const nextHistory=[...history,stage]; const nextAnswers={...answers,[HSA_CASE_ANSWER_KEY]:JSON.stringify(nextData)}; setData(nextData);setHistory(nextHistory);setStage(next);setAnswers(nextAnswers);onUpdate(patient.id,next,nextHistory,nextAnswers,Math.max(progress,10),'Hemorragia subaracnoide');window.scrollTo({top:0,behavior:'smooth'}) }
  const back = () => { if(done){setDone(false);return} if(!history.length){onBack?.();return} const previous=history[history.length-1] as Stage; const nextHistory=history.slice(0,-1);setStage(previous);setHistory(nextHistory);onUpdate(patient.id,previous,nextHistory,answers,Math.max(10,progress-20),patient.emergencyState.riskGroup) }
  const restart = () => { const kept:Record<string,string>={};if(answers[UNIVERSAL_ASSESSMENT_ANSWER_KEY])kept[UNIVERSAL_ASSESSMENT_ANSWER_KEY]=answers[UNIVERSAL_ASSESSMENT_ANSWER_KEY];setStage('hsa_reconhecimento');setHistory([]);setAnswers(kept);setData({});setDone(false);setTransition(null);onUpdate(patient.id,'hsa_reconhecimento',[],kept,20,'Hemorragia subaracnoide') }
  const saveLabs=(value:string)=>{const next={...answers,[UNIVERSAL_LAB_RESULTS_KEY]:value,[HSA_CASE_ANSWER_KEY]:JSON.stringify(data)};setAnswers(next);onUpdate(patient.id,stage,history,next,progress,'Hemorragia subaracnoide')}
  const saveTransition=(value:CareTransitionData)=>{const next={...answers,__care_transition_hsa_destino:JSON.stringify(value),[HSA_CASE_ANSWER_KEY]:JSON.stringify(data)};setTransition(value);setAnswers(next);onUpdate(patient.id,stage,history,next,progress,'Hemorragia subaracnoide')}
  const finish=(value?:CareTransitionData)=>{const nextData={...data,disposition:'UTI neurocrítica/centro neurovascular',completedAt:new Date().toISOString()};const next={...answers,...(value?{__care_transition_hsa_destino:JSON.stringify(value)}:{}),[HSA_CASE_ANSWER_KEY]:JSON.stringify(nextData)};setData(nextData);setAnswers(next);setDone(true);onUpdate(patient.id,stage,[...history,stage],next,100,'Hemorragia subaracnoide')}
  const titles:Record<Stage,[string,string]>={hsa_reconhecimento:['Suspeita de hemorragia subaracnoide','Reconheça uma emergência neurológica tempo-dependente.'],hsa_imagem:['Neuroimagem e confirmação','TC sem contraste é o exame inicial; investigação adicional depende do tempo e da suspeita.'],hsa_estabilizacao:['Estabilização neurocrítica','Reduza variabilidade e hipertensão grave sem causar hipotensão.'],hsa_tratamento_aneurisma:['Aneurisma e complicações','Garanta avaliação neurovascular e tratamento definitivo precoce.'],hsa_destino:['Transição neurocrítica','O atendimento permanece ativo até a passagem formal.']}
  const [title,subtitle]=titles[stage]
  return <div className="min-h-screen bg-gradient-to-b from-slate-50 via-white to-violet-50/40 pb-12"><nav className="sticky top-0 z-50 border-b border-slate-200 bg-white/90 backdrop-blur-xl"><div className="mx-auto flex max-w-7xl items-center justify-between gap-3 px-4 py-4"><div><p className="font-black">{patient.name}</p><p className="text-xs font-semibold text-slate-500">HSA · {progress}%</p></div><div className="flex flex-wrap gap-2"><button type="button" onClick={onComplete} className="rounded-xl border border-slate-300 px-3 py-2 text-sm font-bold"><ChevronLeft className="mr-1 inline h-4 w-4"/>Dashboard</button><button type="button" onClick={back} className="rounded-xl border border-amber-300 bg-amber-50 px-3 py-2 text-sm font-bold"><ArrowLeft className="mr-1 inline h-4 w-4"/>Voltar</button><button type="button" onClick={restart} className="rounded-xl border border-violet-300 bg-violet-50 px-3 py-2 text-sm font-bold"><RotateCcw className="mr-1 inline h-4 w-4"/>Reiniciar</button></div></div></nav><header className="bg-gradient-to-r from-rose-900 via-violet-900 to-slate-950 px-5 py-7 text-white"><div className="mx-auto flex max-w-6xl items-center gap-4"><span className="rounded-2xl bg-white/15 p-3"><Brain className="h-8 w-8"/></span><div><p className="text-xs font-black uppercase tracking-[.2em] text-white/70">Protocolo interativo neurovascular</p><h1 className="mt-1 text-2xl font-black sm:text-3xl">{title}</h1><p className="mt-1 text-sm text-white/85">{subtitle}</p></div></div></header><main className="mx-auto mt-7 max-w-6xl px-4 sm:px-6">{done?<section className="space-y-6"><div className="rounded-3xl bg-gradient-to-br from-emerald-600 to-teal-700 p-7 text-white"><CheckCircle2 className="h-12 w-12"/><h2 className="mt-3 text-3xl font-black">Plano neurocrítico registrado</h2><p className="mt-2">Imagem, estabilização, tratamento definitivo, vigilância e destino foram preservados.</p></div><div className="grid gap-3 sm:grid-cols-2">{onOpenReport&&<button type="button" onClick={onOpenReport} className="rounded-xl border border-violet-300 bg-white px-5 py-4 font-extrabold text-violet-900"><FileText className="mr-2 inline"/>Abrir relatório</button>}<button type="button" onClick={onComplete} className="rounded-xl bg-violet-900 px-5 py-4 font-extrabold text-white">Concluir e ir ao dashboard</button></div></section>:<section className="space-y-6 rounded-3xl border border-slate-200 bg-white p-5 shadow-xl sm:p-7">
    {stage==='hsa_reconhecimento'&&<><div className="grid gap-3 md:grid-cols-2">{recognition.map(([id,label])=><Choice key={id} selected={(data.findings||[]).includes(id)} title={label} onClick={()=>update({findings:toggle(data.findings,id)})}/>)}</div><div className="grid gap-3 md:grid-cols-2">{initialMeasures.map(([id,label])=><Choice key={id} selected={(data.initialMeasures||[]).includes(id)} title={label} danger={id==='specialist'} onClick={()=>update({initialMeasures:toggle(data.initialMeasures,id)})}/>)}</div><button type="button" disabled={!(data.findings||[]).length||(data.initialMeasures||[]).length<4} onClick={()=>persist('hsa_imagem')} className="w-full rounded-xl bg-violet-900 px-5 py-4 font-extrabold text-white disabled:bg-slate-300">Prosseguir para neuroimagem</button></>}
    {stage==='hsa_imagem'&&<><div className="rounded-2xl border border-red-300 bg-red-50 p-4 text-red-950"><AlertTriangle className="mr-2 inline"/><strong>TC de crânio sem contraste com prioridade imediata.</strong> Exames laboratoriais devem ocorrer em paralelo.</div><div className="grid gap-3 md:grid-cols-3">{([['confirmed','Sangramento subaracnoide confirmado'],['negative_high_suspicion','TC sem sangue, mas suspeita clínica permanece alta'],['alternative','HSA afastada; hipótese alternativa predominante']] as const).map(([id,label])=><Choice key={id} selected={data.ctResult===id} title={label} danger={id==='confirmed'} onClick={()=>update({ctResult:id,additionalInvestigation:undefined})}/>)}</div>{data.ctResult==='confirmed'&&<div className="grid gap-3 md:grid-cols-2"><Choice selected={data.vascularImaging==='cta'} title="Angiotomografia cerebral para definir aneurisma" onClick={()=>update({vascularImaging:'cta'})}/><Choice selected={data.vascularImaging==='transfer'} title="Angiografia indisponível — transferir sem atrasar estabilização" danger onClick={()=>update({vascularImaging:'transfer'})}/></div>}{data.ctResult==='negative_high_suspicion'&&<div className="grid gap-3 md:grid-cols-2"><Choice selected={data.additionalInvestigation==='lp'} title="Punção lombar após revisar tempo, imagem e contraindicações" description="Analisar conforme protocolo neurológico local; não usar como etapa automática em todo paciente." onClick={()=>update({additionalInvestigation:'lp'})}/><Choice selected={data.additionalInvestigation==='specialist_imaging'} title="Imagem vascular/avaliação especializada para investigação adicional" onClick={()=>update({additionalInvestigation:'specialist_imaging'})}/></div>}<UniversalLabNotebook value={answers[UNIVERSAL_LAB_RESULTS_KEY]} onChange={saveLabs} title="Exames paralelos" suggestedTests={['Hemograma e plaquetas','Glicemia','Sódio e eletrólitos','Creatinina','Coagulograma','Tipagem e prova de compatibilidade']}/><button type="button" disabled={!data.ctResult||(data.ctResult==='confirmed'&&!data.vascularImaging)||(data.ctResult==='negative_high_suspicion'&&!data.additionalInvestigation)} onClick={()=>data.ctResult==='alternative'?finish():persist('hsa_estabilizacao')} className="w-full rounded-xl bg-violet-900 px-5 py-4 font-extrabold text-white disabled:bg-slate-300">Registrar decisão de imagem</button></>}
    {stage==='hsa_estabilizacao'&&<><div className="grid gap-3 md:grid-cols-2"><label className="font-bold">Pressão arterial atual<input value={data.currentPressure||''} onChange={e=>update({currentPressure:e.target.value})} className="mt-2 w-full rounded-xl border border-slate-300 p-3" placeholder="Ex.: 198/112 mmHg"/></label><label className="font-bold">Meta individual definida pela equipe<input value={data.pressureTarget||''} onChange={e=>update({pressureTarget:e.target.value})} className="mt-2 w-full rounded-xl border border-slate-300 p-3" placeholder="Registrar alvo e limites de segurança"/></label></div><p className="rounded-xl bg-amber-50 p-4 text-sm text-amber-950"><strong>Antes de tratar o aneurisma:</strong> controlar hipertensão grave com agente titulável de curta ação, evitando hipotensão, quedas abruptas e grande variabilidade. Não aplicar um alvo rígido universal sem considerar perfusão cerebral.</p><div className="grid gap-3 md:grid-cols-3">{[['nicardipine','Nicardipina titulável'],['labetalol','Labetalol titulável'],['protocol','Agente do protocolo neurocrítico local']].map(([id,label])=><Choice key={id} selected={data.pressureAgent===id} title={label} onClick={()=>update({pressureAgent:id})}/>)}</div><div className="grid gap-3 md:grid-cols-2">{stabilization.map(([id,label])=><Choice key={id} selected={(data.stabilization||[]).includes(id)} title={label} onClick={()=>update({stabilization:toggle(data.stabilization,id)})}/>)}</div><button type="button" disabled={!data.currentPressure||!data.pressureTarget||!data.pressureAgent||(data.stabilization||[]).length<4} onClick={()=>persist('hsa_tratamento_aneurisma')} className="w-full rounded-xl bg-violet-900 px-5 py-4 font-extrabold text-white disabled:bg-slate-300">Registrar estabilização</button></>}
    {stage==='hsa_tratamento_aneurisma'&&<><div className="grid gap-3 md:grid-cols-3">{[['endovascular','Tratamento endovascular'],['surgical','Clipagem cirúrgica'],['transfer','Centro sem recurso — transferência neurovascular monitorizada']].map(([id,label])=><Choice key={id} selected={data.aneurysmPlan===id} title={label} danger={id==='transfer'} onClick={()=>update({aneurysmPlan:id})}/>)}</div><Choice selected={Boolean(data.definitiveTiming)} title="Tratamento do aneurisma organizado o mais cedo possível, preferencialmente em até 24 horas" danger onClick={()=>update({definitiveTiming:!data.definitiveTiming})}/><div className="grid gap-3 md:grid-cols-2">{surveillance.map(([id,label])=><Choice key={id} selected={(data.surveillance||[]).includes(id)} title={label} onClick={()=>update({surveillance:toggle(data.surveillance,id)})}/>)}</div><button type="button" disabled={!data.aneurysmPlan||!data.definitiveTiming||(data.surveillance||[]).length<4} onClick={()=>persist('hsa_destino')} className="w-full rounded-xl bg-violet-900 px-5 py-4 font-extrabold text-white disabled:bg-slate-300">Solicitar UTI neurocrítica</button></>}
    {stage==='hsa_destino'&&<UniversalCareTransition destination="icu" context="hemorragia subaracnoide neurocirurgia neurointervenção aneurisma" value={transition} onChange={saveTransition} onConfirmed={finish}/>}<button type="button" onClick={back} className="inline-flex items-center gap-2 rounded-xl border border-slate-300 px-4 py-3 font-bold"><ArrowLeft className="h-4 w-4"/>Voltar</button>
  </section>}</main></div>
}
